spring.application.name=pb215

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.profiles.active=dev

# CORS allowed frontend origin(s). Override in production with env var APP_FRONTEND_URL
app.frontend.url=http:///127.0.0.1:5173